"""Hand-verified ground-truth labels: raw ``test_name`` → canonical biomarker key.

These are the gold labels for evaluating the resolvers (rule-based in
``biomarkers.py``, LLM in ``llm.py``). They were assigned by hand over the 148
distinct names in the real export and cover the specimen-disambiguation cases
(urine vs blood WBC/RBC) and the Hungarian ↔ abbreviation synonyms. The
rule-based alias dictionary targets this vocabulary, so its accuracy reflects
curation effort; the LLM resolver never sees these labels or the aliases.

The names are lab vocabulary (which analytes were measured), not measured
values — no health results appear here.
"""

from __future__ import annotations

GOLD: dict[str, str] = {
    "Albumin": "albumin",
    "Albumin (A)": "albumin",
    "Alkalikus foszfatáz": "alp",
    "Alkalikus foszfatáz (A)": "alp",
    "Androsztendion (A)": "androstenedione",
    "Anti müller hormon (AMH-plusz)": "amh",
    "Anti müller hormon (AMH-plusz) (A)": "amh",
    "B12 vitamin": "vitamin_b12",
    "B12 vitamin (A)": "vitamin_b12",
    "Baktérium": "urine_bacteria",
    "Bazofil granulocita #": "basophils_abs",
    "Bazofil granulocita # (A)": "basophils_abs",
    "Bazofil granulocita %": "basophils_pct",
    "Bazofil granulocita % (A)": "basophils_pct",
    "Bilirubin": "bilirubin_total",
    "Bioaktív tesztoszteron": "testosterone_bioactive",
    "Bioaktív tesztoszteron %": "testosterone_bioactive_pct",
    "C reaktív protein (CRP)": "crp",
    "C reaktív protein ultraszenzitív (hsCRP) (A)": "hscrp",
    "D vitamin (25OH)": "vitamin_d",
    "D vitamin (25OH) (A)": "vitamin_d",
    "DHEA szulfát": "dhea_s",
    "DHEA szulfát (A)": "dhea_s",
    "Direkt bilirubin": "bilirubin_direct",
    "Eozinofil granulocita #": "eosinophils_abs",
    "Eozinofil granulocita # (A)": "eosinophils_abs",
    "Eozinofil granulocita %": "eosinophils_pct",
    "Eozinofil granulocita % (A)": "eosinophils_pct",
    "FSH": "fsh",
    "Fajsúly": "urine_specific_gravity",
    "Fehérje": "urine_protein",
    "Fehérvérsejt": "urine_wbc",
    "Fehérvérsejtszám": "wbc",
    "Fehérvérsejtszám (A)": "wbc",
    "Ferritin": "ferritin",
    "Ferritin (A)": "ferritin",
    "Follikulus stimuláló hormon (FSH)": "fsh",
    "Follikulus stimuláló hormon (FSH) (A)": "fsh",
    "Fólsav": "folate",
    "GOT (ASAT)": "ast",
    "GOT (ASAT) (A)": "ast",
    "GPT (ALAT)": "alt",
    "GPT (ALAT) (A)": "alt",
    "Gamma GT (GGT)": "ggt",
    "Gamma GT (GGT) (A)": "ggt",
    "Glukóz": "glucose_fasting",
    "Glükóz (éhgyomri,0 perces vércukor) - plazma": "glucose_fasting",
    "Glükóz 0'(Terhelés előtt, fluoridos cső)": "glucose_fasting",
    "HDL koleszterin": "hdl",
    "HDL koleszterin (A)": "hdl",
    "HPV DNS": "hpv_dna",
    "Hematokrit": "hematocrit",
    "Hematokrit (A)": "hematocrit",
    "Hemoglobin": "hemoglobin",
    "Hemoglobin (A)": "hemoglobin",
    "Hemoglobin (VVT)": "urine_hemoglobin",
    "Homocisztein": "homocysteine",
    "Húgysav": "uric_acid",
    "Húgysav (A)": "uric_acid",
    "Karbamid": "urea",
    "Karbamid (A)": "urea",
    "Keton": "urine_ketones",
    "Koleszterin": "cholesterol_total",
    "Koleszterin (A)": "cholesterol_total",
    "Kortizol": "cortisol",
    "Kortizol - szérum": "cortisol",
    "Kortizol - szérum (A)": "cortisol",
    "Kreatinin": "creatinine",
    "Kreatinin (A)": "creatinine",
    "Kálium (K)": "potassium",
    "Kálium (K) (A)": "potassium",
    "LDL koleszterin": "ldl",
    "LDL koleszterin (A)": "ldl",
    "LH": "lh",
    "Laphámsejt": "urine_epithelial",
    "Limfocita #": "lymphocytes_abs",
    "Limfocita # (A)": "lymphocytes_abs",
    "Limfocita %": "lymphocytes_pct",
    "Limfocita % (A)": "lymphocytes_pct",
    "Luteinizáló hormon (LH)": "lh",
    "Luteinizáló hormon (LH) (A)": "lh",
    "MCH": "mch",
    "MCH (A)": "mch",
    "MCHC": "mchc",
    "MCHC (A)": "mchc",
    "MCV": "mcv",
    "MCV (A)": "mcv",
    "MPV": "mpv",
    "MPV (A)": "mpv",
    "Magvas VVT abszolút szám": "nrbc_abs",
    "Monocita #": "monocytes_abs",
    "Monocita # (A)": "monocytes_abs",
    "Monocita %": "monocytes_pct",
    "Monocita % (A)": "monocytes_pct",
    "Neutrofil granulocita #": "neutrophils_abs",
    "Neutrofil granulocita # (A)": "neutrophils_abs",
    "Neutrofil granulocita %": "neutrophils_pct",
    "Neutrofil granulocita % (A)": "neutrophils_pct",
    "Nitrit": "urine_nitrite",
    "Nátrium (Na)": "sodium",
    "Nátrium (Na) (A)": "sodium",
    "Progeszteron": "progesterone",
    "Prolaktin (PRL)": "prolactin",
    "Prolaktin (PRL) (A)": "prolactin",
    "RDW-CV": "rdw",
    "RDW-CV (A)": "rdw",
    "Szabad T3": "ft3",
    "Szabad T3 (A)": "ft3",
    "Szabad T4": "ft4",
    "Szabad T4 (A)": "ft4",
    "Szabad tesztoszteron": "testosterone_free",
    "Szabad tesztoszteron %": "testosterone_free_pct",
    "Szexhormon kötő fehérje (SHBG)": "shbg",
    "Szexhormon kötő fehérje (SHBG) (A)": "shbg",
    "Tireoglobulin elleni antitest (anti-Tg GEN2) (A)": "tg_ab",
    "Tireoidea peroxidáz auto antitest (aTPO GEN2)": "tpo_ab",
    "Tireoidea peroxidáz elleni antitest (aTPO)": "tpo_ab",
    "Tireoidea peroxidáz elleni antitest (aTPO) (A)": "tpo_ab",
    "Tireoidea stimuláló hormon (TSH)": "tsh",
    "Tireoidea stimuláló hormon (TSH) (A)": "tsh",
    "Tireotropin receptor stimuláló immunglobulinok (TSI)": "trab",
    "Totál bilirubin": "bilirubin_total",
    "Totál bilirubin (A)": "bilirubin_total",
    "Totál tesztoszteron": "testosterone_total",
    "Totál tesztoszteron (A)": "testosterone_total",
    "Transzferrin": "transferrin",
    "Transzferrin (A)": "transferrin",
    "Transzferrin szaturáció": "transferrin_saturation",
    "Triglicerid": "triglycerides",
    "Trigliceridek": "triglycerides",
    "Trigliceridek (A)": "triglycerides",
    "Trombocitaszám": "platelets",
    "Trombocitaszám (A)": "platelets",
    "Urobilinogén": "urine_urobilinogen",
    "Vas (Fe)": "iron",
    "Vas (Fe) (A)": "iron",
    "Vérsejtsüllyedés": "esr",
    "Vörösvérsejt": "urine_rbc",
    "Vörösvérsejtszám": "rbc",
    "Vörösvérsejtszám (A)": "rbc",
    "eGFR-EPI": "egfr",
    "eGFR-EPI (mL/min/1.73m2)": "egfr",
    "pH": "urine_ph",
    "Összfehérje": "total_protein",
    "Összfehérje (A)": "total_protein",
    "Ösztradiol": "estradiol",
    "Ösztradiol (E2)": "estradiol",
    "Ösztradiol (E2) (A)": "estradiol",
}
